// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwssoWo4UWJ5jgcS633RzrOkGPKCQDiQc',
    appId: '1:374135987086:web:5c6831f2f5163b1831e2df',
    messagingSenderId: '374135987086',
    projectId: 'studen-zone',
    authDomain: 'studen-zone.firebaseapp.com',
    storageBucket: 'studen-zone.firebasestorage.app',
    measurementId: 'G-S5BBBB4P1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAchxT_dvSSzWsi8TYY-CpYrQpmvKaeZw',
    appId: '1:374135987086:android:7ab1d394506b6d0831e2df',
    messagingSenderId: '374135987086',
    projectId: 'studen-zone',
    storageBucket: 'studen-zone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkUm5oQuZ0B8jfDW95NjkkeQxoN7xXd3g',
    appId: '1:374135987086:ios:f86cd83e15a2752831e2df',
    messagingSenderId: '374135987086',
    projectId: 'studen-zone',
    storageBucket: 'studen-zone.firebasestorage.app',
    iosBundleId: 'com.example.studentZone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkUm5oQuZ0B8jfDW95NjkkeQxoN7xXd3g',
    appId: '1:374135987086:ios:f86cd83e15a2752831e2df',
    messagingSenderId: '374135987086',
    projectId: 'studen-zone',
    storageBucket: 'studen-zone.firebasestorage.app',
    iosBundleId: 'com.example.studentZone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwssoWo4UWJ5jgcS633RzrOkGPKCQDiQc',
    appId: '1:374135987086:web:42d17422210da26d31e2df',
    messagingSenderId: '374135987086',
    projectId: 'studen-zone',
    authDomain: 'studen-zone.firebaseapp.com',
    storageBucket: 'studen-zone.firebasestorage.app',
    measurementId: 'G-C2FQ8D8DQT',
  );
}
